# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20161112_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffee.Drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(to='coffee.Ingredient'),
        ),
    ]
